In [4]:
import numpy as np

a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])


In [5]:
a[a < 0]

array([-2, -1, -6, -7])

In [6]:
a[a > 0]

array([ 4, 10, 12, 23,  3])

In [11]:
a_new = a[a > 0] 
a_new[a_new % 2 == 0]

array([ 4, 10, 12])

In [12]:
a[a + 3]

IndexError: index 13 is out of bounds for axis 0 with size 12